### PR TITLE
feat: move sources into apps folder

### LINKED ISSUE #1347: 폴더 구조 정리
### Describe the problem and solution

Monorepo에 맞는 폴더 구조로 변경합니다.
지금은 root에 폴더랑 파일이 너무 많아서 가독성이 떨어져요 😢

```
codedang
├── apps
│   ├── backend
│   ├── frontend
│   ├── frontend-client
│   ├── grafana-logs
│   ├── infra
│   └── iris
├── collection
│   ├── admin
│   └── client
├── docs
│   ├── intro
│   ├── project
│   ...
│   └── user
├── commitlint.config.ts
├── docker-compose.yml
├── ...
└── skkuding.code-workspace
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/skkuding/next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md)
- [X] Check that there isn't already an issue

### PR DESCRIPTION
**Pull request by dotoleeoak**
### Description

Close #1347

- 폴더 정리해요 (서비스들은 전부 apps 폴더 안으로)
- 옛날 프론트 코드 지워요 (Vue)

---

### Before submitting the PR, please make sure you do the following

- [x] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md)
- [x] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md#pr-and-branch) and follow the [Commit Convention](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md#commit-convention)
- [x] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
- [ ] Ideally, include relevant tests that fail without this PR but pass with it.

### CODE REVIEW

**Comment by dotoleeoak** [comment]
@aintbe 
- 따로 필요 없을 거 같아서 지웠어요 필요하면 git으로 참고하려고...?
- 그것도 생각했는데, `services`, `packages` 같은 이름보다 `apps`가 더 정확한 이름이라고 생각해서 이렇게 하긴 했어요

**Comment by dayongkr** [comment]
repo 분리해서 vue 프로젝트 남겨두는 건 어떨까요??

**Comment by dotoleeoak** [comment]
@aintbe @dayongkr Repo 새로 생성했습니당
https://github.com/skkuding/codedang-frontend-legacy

**Review by aintbe — APPROVED** [review]
정 리 조 아

**Pull request merged**
